apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt
  namespace: speech-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stt
  template:
    metadata:
      labels:
        app: stt
    spec:
      containers:
        - name: stt
          image: ghcr.io/uncensored-ai-inc/moshi-server:latest
          command: ['worker', '--config', 'configs/stt.toml']
          ports:
            - containerPort: 8080
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-token
                  key: token
          volumeMounts:
            - name: cargo-registry-stt
              mountPath: /root/.cargo/registry
            - name: stt-target
              mountPath: /app/target
            - name: uv-cache
              mountPath: /root/.cache/uv
            - name: models
              mountPath: /models
            - name: stt-logs
              mountPath: /logs
          resources:
            requests:
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
      nodeSelector:
        nvidia.com/gpu.present: 'true'
      tolerations:
        - key: accelerator
          operator: Equal
          value: 'true'
          effect: NoSchedule
      volumes:
        - name: cargo-registry-stt
          emptyDir: {}
        - name: stt-target
          emptyDir: {}
        - name: uv-cache
          emptyDir: {}
        - name: models
          emptyDir: {}
        - name: stt-logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: stt
  namespace: speech-io
spec:
  selector:
    app: stt
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
