apiVersion: apps/v1
kind: Deployment
metadata:
  name: stt
  namespace: speech-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stt
  template:
    metadata:
      labels:
        app: stt
    spec:
      containers:
        - name: stt
          image: ghcr.io/uncensored-ai-inc/moshi-server:latest
          args: ['worker', '--config', 'configs/stt.toml']
          ports:
            - containerPort: 8080
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-token
                  key: token
            - name: NVIDIA_VISIBLE_DEVICES
              value: 'all'
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: 'compute,utility'
            - name: PATH
              value: '/root/.cargo/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
            - name: LD_LIBRARY_PATH
              value: '/usr/local/cuda/lib64:/usr/local/cuda/lib'
            - name: CUDA_HOME
              value: '/usr/local/cuda'
          volumeMounts:
            - name: shared-cargo-registry
              mountPath: /root/.cargo/registry
            - name: stt-target
              mountPath: /app/target
            - name: shared-uv-cache
              mountPath: /root/.cache/uv
            - name: shared-models
              mountPath: /models
            - name: stt-logs
              mountPath: /logs
          resources:
            requests:
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
      nodeSelector:
        nvidia.com/gpu.present: 'true'
      tolerations:
        - key: nvidia.com/gpu
          operator: Equal
          value: 'true'
          effect: NoSchedule
      volumes:
        - name: shared-cargo-registry
          emptyDir:
            sizeLimit: 5Gi
        - name: stt-target
          emptyDir:
            sizeLimit: 10Gi
        - name: shared-uv-cache
          emptyDir:
            sizeLimit: 10Gi
        - name: shared-models
          emptyDir:
            sizeLimit: 5Gi
        - name: stt-logs
          emptyDir:
            sizeLimit: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: stt
  namespace: speech-io
spec:
  selector:
    app: stt
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
