name: Docker Build

on:
  push:
    branches:
      - prod
      - main
  pull_request:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up lowercase repository owner
        run: |
          echo "REPO_OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: hot-reloading
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/unmute-backend:latest
            ghcr.io/${{ env.REPO_OWNER_LC }}/unmute-backend:${{ github.sha }}

      - name: Make backend package public
        run: |
          gh api /orgs/${{ github.repository_owner }}/packages/container/unmute-backend --method PATCH --field visibility=public || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up lowercase repository owner
        run: |
          echo "REPO_OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/unmute-frontend:latest
            ghcr.io/${{ env.REPO_OWNER_LC }}/unmute-frontend:${{ github.sha }}

      - name: Make frontend package public
        run: |
          gh api /orgs/${{ github.repository_owner }}/packages/container/unmute-frontend --method PATCH --field visibility=public || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-moshi-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up lowercase repository owner
        run: |
          echo "REPO_OWNER_LC=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push moshi-server image
        uses: docker/build-push-action@v5
        with:
          context: ./services/moshi-server
          file: ./services/moshi-server/public.Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/moshi-server:latest
            ghcr.io/${{ env.REPO_OWNER_LC }}/moshi-server:${{ github.sha }}

      - name: Make moshi-server package public
        run: |
          gh api /orgs/${{ github.repository_owner }}/packages/container/moshi-server --method PATCH --field visibility=public || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
